Repository cardano-foundation/CIPs, pull requests merged in 2021-11, with the labels that each got.

#116 CIP-0027 | Standardization of royalties
  CIP-0010/registry.json
  CIP-0027/CIP-0027.md
Labels: tentative CIP, PR Status: LAST CHECK

#88 CIP-0030 | Dapp-Connector
  CIP-0030/README.md
Labels: tentative CIP, Type: Standards, PR Status: LAST CHECK

#145 Turn CIP-0002, CIP-0003 & CIP-0005 into 'active'
  CIP-0002/README.md
  CIP-0003/README.md
  CIP-0005/README.md
  README.md
Labels: Minor change

#155 Fix CI build for authors without email.
  scripts/build.js
Labels: repository structure, correction

#147 Cip 0010 cardahub metadata
  CIP-0010/registry.json
Labels: Minor change, Update

#152 CIP-0007 to Proposed
  CIP-0007/README.md
Labels: Minor change, Update

#150 Improve readability of CIP-0019
  CIP-0019/README.md
Labels: Minor change, Update
