Repository cardano-foundation/CIPs, pull requests merged in 2021-12, with the labels that each got.

#166 Moving CIPs 9, 10 & 11 to 'Active'
  CIP-0009/README.md
  CIP-0010/README.md
  CIP-0011/README.md
  README.md
Labels: Update

#173 CIP-0019 [MINOR] - Some corrections
  CIP-0019/CIP-0019-cardano-addresses.abnf
  CIP-0019/README.md
Labels: Minor change, correction

#172 Align headers with other CIP (start with H2)
  CIP-0002/README.md
Labels: Minor change

#140 CIP-0028 | Alonzo Protocol Parameter Description
  CIP-0028/README.md
Labels: tentative CIP, Type: Informational, PR Status: LAST CHECK

#179 docs: Link Rust message signing implementation
  CIP-0008/README.md
Labels: Minor change

#174 Fix CIP-0003 rotten ED25519-BIP32 link
  CIP-0003/README.md
Labels: Minor change
