Repository cardano-foundation/CIPs, pull requests merged in 2022-02, with the labels that each got.

#184 CIP27: Change CIP Type and Status
  CIP-0027/README.md
Labels: Minor change, correction

#219 Fixing Type
  CIP-0005/README.md
Labels: correction

#157 CIP-0021 | Add multisig changes
  CIP-0021/README.md
Labels: Minor change, Update
