Repository cardano-foundation/CIPs, pull requests merged in 2022-01, with the labels that each got.

#158 CIP 34: Network Registry
  CIP-0034/README.md
  CIP-0034/registry.json
  CIP-0034/schema.json
Labels: tentative CIP, Type: Informational, PR Status: LAST CHECK

#180 CIP9: typo
  CIP-0009/README.md
Labels: correction

#197 CIP-0025: Fix commas in JSON
  CIP-0025/README.md
Labels: Minor change, correction

#195 CIP 3: add BitBox02 to the table of derivation methods
  CIP-0003/Ledger_BitBox02.md
  CIP-0003/README.md
Labels: Minor change

#193 Specified asset name encoding
  CIP-0025/README.md
Labels: Minor change

#161 CIP-33: Reference scripts
  CIP-0033/README.md
Labels: tentative CIP, Type: Standards
