Repository cardano-foundation/CIPs, pull requests merged in 2022-09, with the labels that each got.

#313 CIP-0021 | Add Babbage changes
  CIP-0021/README.md
Labels: Update

#304 absolute paths for remaining cross-CIP relative links
  CIP-0011/README.md
  CIP-0035/README.md
Labels: Correction

#163 CIP-0037? | Dynamic Saturation based on Pledge
  CIP-0037/README.md
Labels: Candidate CIP, Standard

#316 Top-Level README Chore / Editors List Update
  CIP-0001/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#324 update registry.json: ape society amphitheatre
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#307 CIP-0060? | Music Token Metadata
  CIP-0060/README.md
  CIP-0060/cddl/version-1.cddl
  README.md
Labels: Candidate CIP, Process

#320 Create Meeting Notes 51
  BiweeklyMeetings/2022-08-16.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#327 top README: link to meeting recordings
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#328 Update registry.json - Shareslake bridge metadata key
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#329 CIP-0036 - Map keys are unsigned int values not strings
  CIP-0036/test-vector.md
Labels: Correction

#333 CIP-0059 | Add dates and slot numbers to the table
  CIP-0059/feature-table.md
Labels: Update

#338 Update top-level README tables & status for a few now-active proposals.
  CIP-0031/README.md
  CIP-0032/README.md
  CIP-0033/README.md
  CIP-0040/README.md
  CIP-0042/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#326 Create Meeting Notes 52.md
  BiweeklyMeetings/2022-09-06.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#334 Top-Level README | Fix CIP-0005 status
  README.md
Labels: Correction
