Repository cardano-foundation/CIPs, pull requests merged in 2022-03, with the labels that each got.

#153 Fair min fees
  CIP-0023/README.md
Labels: Minor change, Update

#160 CIP-32: Inline datums
  CIP-0032/README.md
Labels: tentative CIP, Type: Standards

#148 CIP-0030: update to api.signData()
  CIP-0030/README.md
Labels: Minor change, Update

#227 Add more details on main's README
  README.md
Labels: documentation, Minor change
