Repository cardano-foundation/CIPs, pull requests merged in 2022-08, with the labels that each got.

#302 Create Meeting Notes 48
  BiweeklyMeetings/2022-07-05.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#305 updates to CIP meeting links and text since Discord migration
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#214 CIP-0027 | Fix status header
  CIP-0027/README.md
Labels: Update

#311 Update README merged, under review and stalled proposals.
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#315 missing parenthesis in Babbage min utxo calc
  CIP-0055/README.md
Labels: Correction

#306 Create Meeting Notes 49
  BiweeklyMeetings/2022-07-19.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
