Repository cardano-foundation/CIPs, pull requests merged in 2022-07, with the labels that each got.

#216 CIP-0040? | Collateral output
  CIP-0040/README.md
  README.md
Labels: Candidate CIP, Standard

#287 fix CIP-0040 table omissions
  README.md
Labels: Correction

#274 CIP-0059? | Terminology Surrounding Core Features
  CIP-0059/README.md
  CIP-namesSurroundingFeatures/feature-table.md
Labels: Candidate CIP, Informational

#275 Update line numbers of cardano-serialisation-lib
  CIP-0008/README.md
Labels: Correction

#289 Broken links in various CIPs
  CIP-0003/README.md
  CIP-0035/README.md
Labels: Correction

#293 CIP-0055 correction: constant overhead in babbageMinUTxOValue
  CIP-0055/README.md
Labels: Correction

#291 CIP-0059 correction: table file didn't get moved
  CIP-0059/feature-table.md
Labels: Correction

#292 CIP-0055 correction: spelling error
  CIP-0055/README.md
Labels: Correction

#295 Fix website build failures & CIPs' assets copy
  CIP-0052/README.md
  CIP-0059/README.md
  scripts/build.js
  templates/annexe.hbs
Labels: Correction, Bi-Weekly Notes / Editorial Housekeeping

#297 Register new CIP-10 metadatum label for Open Badges v2.0 compliant transaction metadata
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#220 CIP-0381? | Plutus support for pairings over curve Bls12-381
  CIP-0381/README.md
Labels: Standard

#263 CIP-0054? | Cardano Smart NFTs
  CIP-0054/README.md
  README.md
Labels: Candidate CIP, Process, Last Check, Waiting for Author
