Repository cardano-foundation/CIPs, pull requests merged in 2022-10, with the labels that each got.

#347 CIP-0036 | Changed terminology in schema to match README specification
  CIP-0036/schema.cddl
Labels: Correction

#341 CIP-0025 | Update "image" Spec Based on Feedback
  CIP-0025/README.md
Labels: Update

#339 CIP-0030 | Fix some spelling errors
  CIP-0030/README.md
Labels: Correction

#299 CIP-0068? | Datum Metadata Standard
  CIP-0068/README.md
  CIP-0068/ref_impl/README.md
  CIP-0068/ref_impl/offchain.ts
  CIP-0068/ref_impl/onchain.hs
Labels: Candidate CIP, Process

#264 CIP-0026 | subject properties return multiple claims
  CIP-0026/README.md
Labels: Update

#350 CIP Editors meeting #55 housekeeping
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#352 CIP-0010 Finitum.io token bridge txs metadata
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#353 CIP0025 | retitle to Media NFT Metadata Standard
  CIP-0025/README.md
  README.md
Labels: Correction

#250 CIP-0049? | ECDSA and Schnorr signatures in Plutus Core
  CIP-0049/README.md
Labels: Candidate CIP, Standard

#362 CIP editor meeting #56's housekeeping
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#298 CIP-0067? | Asset Name Label Registry
  CIP-0067/README.md
  CIP-0067/registry.json
  CIP-0067/registry.schema.json
Labels: Candidate CIP, Informational

#331 CIP-0001 | Rework to reflect reality
  .github/CIP-TEMPLATE.md
  CIP-0001/CIP_Flow.png
  CIP-0001/README.md
  CODE_OF_CONDUCT.md
  README.md
  cip-template.md
Labels: Update
