Repository cardano-foundation/CIPs, pull requests merged in 2022-05, with the labels that each got.

#182 CIP-1852: fix broken CIP links
  CIP-1852/README.md
Labels: Minor change, correction

#177 CIP-0005 | Add prefixes for output datum hash and script data hash
  CIP-0005/README.md
Labels: Minor change

#224 Add Proof of Existence record label to registry.json
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#188 CIP-36? | Update CIP-15 to support multi-delegation
  CIP-0036/README.md
  CIP-0036/schema.cddl
  CIP-0036/test-vector.md
Labels: Update

#181 CIP30: getUtxos null instead of undefined
  CIP-0030/README.md
Labels: Minor change

#213 CIP-0033 | update to ban reference scripts in the presence of old scripts
  CIP-0033/README.md
Labels: correction

#218 CIP-0042 | New plutus builtin: serialiseBuiltinData
  CIP-0042/README.md
Labels: Candidate CIP, Standard

#255 Add merged CIP and new candidates to top-level README table.
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#266 Fix value for a0
  CIP-0009/README.md
Labels: Update

#256 CIP-0014, CIP-0015, CIP-0016, CIP-0025, CIP-0028, CIP-0029, CIP-1852, CIP-1853, CIP-1855 status updates.
  CIP-0014/README.md
  CIP-0015/README.md
  CIP-0016/README.md
  CIP-0025/README.md
  CIP-0028/README.md
  CIP-0029/README.md
  CIP-1852/README.md
  CIP-1853/README.md
  CIP-1855/README.md
  README.md
Labels: Update
