Repository cardano-foundation/CIPs, pull requests merged in 2022-11, with the labels that each got.

#317 Add Marlowe to metadata label registry
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry, Waiting for Author

#368 CIP-0010 | Add cardanohosts.com metadatum labels
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#367 Add more optional fields. Update state to Active
  CIP-0060/README.md
  CIP-0060/cddl/version-1.cddl
Labels: Update

#370 Editors meeting #57 housekeeping
  CIP-0009/README.md
  CIP-0028/README.md
  CIP-0055/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#388 Update top-level README and CIP/CPS number allocations.
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
