Repository cardano-foundation/CIPs, pull requests merged in 2023-02, with the labels that each got.

#460 Add the Plutus category to a couple of existing CIPs
  CIP-0042/README.md
  CIP-0381/README.md
Labels: Update

#457 CIP-0033 | Typo in README
  CIP-0033/README.md
Labels: Correction

#463 CIP-0059 | Add "Valentine" HF
  CIP-0059/feature-table.md
Labels: Update

#461 CIP-0036 | Fix CDDL naming to match changes in spec from #427
  CIP-0036/schema.cddl
Labels: Update

#464 Update CIP's README accordingly to editors meeting #61
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
