Repository cardano-foundation/CIPs, pull requests merged in 2023-01, with the labels that each got.

#412 CIP-0034 | Include legacy testnet
  CIP-0034/registry.json
Labels: Update

#405 [paradiso.app] remove transaction metadatum labels
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#424 CIP-0026 | Update signatures schema
  CIP-0026/schema.json
Labels: Correction

#426 CIP-0036 | Fixed incorrect CDDL notation and incorrect keys in test vectors
  CIP-0036/schema.cddl
  CIP-0036/test-vector.md
Labels: Correction

#411 CIP-0001 | Fix status anchors, add Categories link
  CIP-0001/README.md
Labels: Correction

#427 CIP-0005, CIP-0036 | Added clarity to voting key definitions
  CIP-0005/README.md
  CIP-0036/README.md
Labels: Update

#406 CIP-0052 | Add public keys to auditor table
  CIP-0052/README.md
Labels: Update, Waiting for Author

#428 CIP-0035 | Redraft to handle Plutus Core language versions
  CIP-0035/README.md
Labels: Update

#434 Edit CIP numbers and top-level README from editors meeting #60's outcome
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#373 CIP-0036 | Change reward address field for Fund 10
  CIP-0036/README.md
  CIP-0036/schema.cddl
  CIP-0036/test-vector.md
Labels: Update

#450 CIP-0001 | Section headers, Path to active, PR submission
  CIP-0001/README.md
Labels: Update

#452 CIP-0001 | add Path to Active to Table of Contents
  CIP-0001/README.md
Labels: Correction

#453 Rework CIP-0005's headers and sections + remove h1 headers from various CIPs
  .github/CIP-TEMPLATE.md
  .github/CPS-TEMPLATE.md
  CIP-0001/README.md
  CIP-0002/README.md
  CIP-0003/README.md
  CIP-0004/README.md
  CIP-0005/README.md
  CIP-0013/README.md
  CIP-0020/README.md
  CIP-0031/README.md
  CIP-0032/README.md
  CIP-0033/README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
