Repository cardano-foundation/CIPs, pull requests merged in 2023-12, with the labels that each got.

#634 CIP-0010 | Add proof of origin metadata label
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#556 CIP-0100? | Governance Metadata
  CIP-0010/registry.json
  CIP-0100/README.md
  CIP-0100/cip-0100.common.jsonld
  CIP-0100/cip-0100.common.schema.json
  CIP-0100/example.body.canonical
  CIP-0100/example.canonical
  CIP-0100/example.json
Labels: Last Check, Category: Metadata

#467 CIP-0088? | Token Policy Registration
  CIP-0010/registry.json
  CIP-0088/CIPs/0025/CIP25_v1.cddl
  CIP-0088/CIPs/0025/CIP25_v1.json
  CIP-0088/CIPs/0025/CIP25_v1.schema.json
  CIP-0088/CIPs/0025/README.md
  CIP-0088/CIPs/0026/CIP26_v1.cddl
  CIP-0088/CIPs/0026/CIP26_v1.json
  CIP-0088/CIPs/0026/CIP26_v1.schema.json
  CIP-0088/CIPs/0026/README.md
  CIP-0088/CIPs/0027/CIP27_v1.cddl
  CIP-0088/CIPs/0027/CIP27_v1.json
  CIP-0088/CIPs/0027/CIP27_v1.schema.json
  CIP-0088/CIPs/0027/README.md
  CIP-0088/CIPs/0048/CIP48_v1.cddl
  CIP-0088/CIPs/0048/README.md
  CIP-0088/CIPs/0060/CIP60_v1.cddl
  CIP-0088/CIPs/0060/README.md
  CIP-0088/CIPs/0068/CIP68_v1.cddl
  CIP-0088/CIPs/0068/CIP68_v1.json
  CIP-0088/CIPs/0068/CIP68_v1.schema.json
  CIP-0088/CIPs/0068/README.md
  CIP-0088/CIPs/0086/CIP86_v1.cddl
  CIP-0088/CIPs/0086/README.md
  CIP-0088/CIPs/README.md
  CIP-0088/CIPs/common/CIP88_Master_v1.cddl
  CIP-0088/CIPs/common/README.md
  CIP-0088/CIPs/common/Token-Project-Details_v1.md
  CIP-0088/CIPs/common/token-project-details_v1.cddl
  CIP-0088/CIPs/common/token-project-details_v1.schema.json
  CIP-0088/CIPs/common/uri-array.schema.json
  CIP-0088/CIPs/template/CIPXXXX_v1.cddl
  CIP-0088/CIPs/template/CIPXXXX_v1.json
  CIP-0088/CIPs/template/CIPXXXX_v1.schema.json
  CIP-0088/CIPs/template/README.md
  CIP-0088/README.md
Labels: Category: Tokens

#637 Update top-level README: post meeting #78
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
