Repository cardano-foundation/CIPs, pull requests merged in 2023-08, with the labels that each got.

#527 CIP-0025 | Restrict to minting (positive amounts)
  CIP-0025/README.md
Labels: Update, Last Check, Category: Tokens

#572 Update top-level README: meeting 70 period
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#573 CIP1694 | Add acknowledgement of workshop participants in French
  CIP-1694/README.fr.md
Labels: Update

#578 CIP-1694 | Add acknowledgements for community workshops
  CIP-1694/README.md
Labels: Update

#562 CIP-0068 | Improve image types and URI descriptions
  CIP-0068/README.md
Labels: Update

#570 CIP-0030 | A few small fixes
  CIP-0030/README.md
Labels: Correction, Category: Wallets

#574 CIP-0050 | Fix relative links
  CIP-0050/README.md
Labels: Correction

#565 CIP-0093 | Update cross-CIP links to anchored relative paths
  CIP-0093/README.md
Labels: Correction

#584 CIP-1854 | Fix typo
  CIP-1854/README.md
Labels: Correction
