Repository cardano-foundation/CIPs, pull requests merged in 2023-05, with the labels that each got.

#455 CIP-0085? | Sums-of-products in Plutus Core
  CIP-0085/README.md
Labels: Last Check, Category: Plutus

#494 CIP-0068 | Add RFT Rich-fungible token support
  CIP-0067/registry.json
  CIP-0068/README.md
Labels: Update, Last Check, CIP-0067: new label, Category: Metadata

#430 CIP-0086? | NFT Metadata Update Oracles
  CIP-0086/README.md
  CIP-0086/cddl/version_1.cddl
  CIP-0086/cddl/version_2.cddl
Labels: Category: Metadata

#484 CIP-0035 | Require proposals for new builtin types to explain how they will be (de)serialized
  CIP-0035/README.md
Labels: Update, Category: Meta

#258 CIP-0057? | Plutus Smart-Contract Blueprints
  CIP-0057/README.md
  CIP-0057/schemas/README.md
  CIP-0057/schemas/plutus-blueprint-argument.json
  CIP-0057/schemas/plutus-blueprint-parameter.json
  CIP-0057/schemas/plutus-blueprint.json
  CIP-0057/schemas/plutus-builtin.json
  CIP-0057/schemas/plutus-data.json
  README.md
Labels: Category: Tools

#514 CIP-0057 | Fix Aiken link
  CIP-0057/README.md
Labels: Correction

#517 Update top-level README for meeting #66 and meantime CIP promotions
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#515 CIP-0010 | Add Agora proposal creation metadata to registry
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#518 Update top-level README with outcome of editor meetings 65 & 66
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
