Repository cardano-foundation/CIPs, pull requests merged in 2023-09, with the labels that each got.

#524 CIP-0101 | Integration of `keccak256` into Plutus
  CIP-0101/README.md
Labels: Category: Plutus

#575 Fix or rationalise Adrestia links
  CIP-0002/README.md
  CIP-0003/README.md
Labels: Correction

#563 CIP-0001 | Add Versioning + other small edits
  .github/CIP-TEMPLATE.md
  CIP-0001/README.md
Labels: Update, Category: Meta

#582 CIP-0050 | Translations: fix Spanish metadata, remove Chinese
  CIP-0050/README.Chinese.md
  CIP-0050/README.es.md
Labels: Correction

#585 CIP-0001 | Allow ISO date if translation source uncommitted
  CIP-0001/README.md
Labels: Update

#589 Update top-level README: meeting #72 promotions
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#591 CIP-0054 | Fix API headers for markdown portability
  CIP-0054/README.md
Labels: Correction

#592 CIP-0029 | Fix JSON schema link
  CIP-0029/README.md
Labels: Correction

#576 CIP-1694 | Design changes after the Edinburgh workshop
  CIP-1694/README.md
Labels: Update, Category: Ledger

#577 CIP-0030 | Encourage namespaced extension endpoints
  CIP-0030/README.md
Labels: Update, Category: Wallets

#509 CIP-0095? | Web-Wallet Bridge | Governance
  CIP-0095/README.md
Labels: Category: Wallets

#595 Update top-level README: meeting #73 promotion
  CIP-0095/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#596 CIP-1694 | French - Design changes after the Edinburgh workshop
  CIP-1694/README.fr.md
Labels: Correction

#594 CIP-0001 | Titles for CIPs with common purpose
  CIP-0001/README.md
Labels: Update
