Repository cardano-foundation/CIPs, pull requests merged in 2023-10, with the labels that each got.

#593 CIP-0025 | Change "NFT" to "token"
  CIP-0010/registry.json
  CIP-0025/README.md
  README.md
Labels: Last Check

#602 CIP-0015 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0015/README.md
Labels: Update

#551 CIP-0102? | Royalty Datum Metadata
  CIP-0067/registry.json
  CIP-0102/README.md
  CIP-0102/ref_impl/TODO.md
Labels: Last Check, CIP-0067: new label, Category: Tokens

#607 Fix link for BIP32-Ed25519 reference paper
  CIP-1852/README.md
Labels: Correction

#606 Update top-level README: post meeting #75
  CIP-0102/README.md
  CPS-0007/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
