Repository cardano-foundation/CIPs, pull requests merged in 2023-11, with the labels that each got.

#613 CIP-0057 | Fix typo
  CIP-0057/README.md
Labels: Correction

#618 Update top-level README: post meeting #76
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#621 Update top-level README: rush new title for CIP-0088
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#612 CIP-0072 | Off-chain schema versioning and schema adjustments
  CIP-0072/README.md
  CIP-0072/version_1_onchain.json
  CIP-0072/version_2.0.0_offchain.json
  CIP-0072/version_2.0.0_onchain.cddl
  CIP-0072/version_2.0.0_onchain.json
Labels: Category: Metadata
