Repository cardano-foundation/CIPs, pull requests merged in 2023-07, with the labels that each got.

#456 CIP-0084? | Ledger evolution (meta)
  CIP-????/README.md
Labels: Last Check, Category: Ledger

#531 Fix status links in top level README
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#481 CPS-0007? | Voltaire era Governance
  CPS-0007/README.md
Labels: Category: Ledger

#529 CIP-0072 | Fold inline schemas into links to companion files
  CIP-0072/README.md
Labels: Update

#536 Top README: update for CIP-0084 consequences to RSS proposals
  .github/CIP-TEMPLATE.md
  .github/CPS-TEMPLATE.md
  CIP-0075/README.md
  CIP-0082/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#540 CIP-0023 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0023/README.md
Labels: Update

#525 CIP-0060 | Fix relative links
  CIP-0060/README.md
Labels: Correction

#521 CIP-0086 | Remove metadata update transaction restrictions
  CIP-0086/README.md
Labels: Update, Last Check

#538 CIP-0024 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0024/README.md
  README.md
Labels: Update

#537 CIP-0007 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0007/README.md
Labels: Update

#542 Extend CIP-0001 to cover internationalized content
  CIP-0001/README.md
Labels: Update, Category: Meta

#548 CIP-1694 correction | Fix ledger spec links
  CIP-1694/README.md
Labels: Correction

#550 CIP-1694 | Update French version to Commit (89bb166)
  CIP-1694/README.fr.md
Labels: Correction

#506 CIP-0381 | Adapt to Plutus bindings
  CIP-0381/README.md
Labels: Update, Last Check, Category: Plutus

#552 Update top-level README: last 2 weeks' activity
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
