Repository cardano-foundation/CIPs, pull requests merged in 2023-06, with the labels that each got.

#321 CIP-0069? | Plutus Script Type Uniformization
  CIP-0069/README.md
Labels: Last Check, Category: Plutus

#519 CIP-0086 | Fix relative links to asset files
  CIP-0086/README.md
Labels: Correction

#502 CIP-0060 | Update to v2
  CIP-0060/README.md
  CIP-0060/cddl/version-2.cddl
Labels: Update, Last Check, Category: Metadata

#496 CIP-0094? | SPO On-chain Polls
  CIP-0010/registry.json
  CIP-0094/CIP-0094_procedure-duration.png
  CIP-0094/README.md
  README.md
Labels: Category: Tools

#355 CIP-0072? | DApp Registration & Discovery
  CIP-0072/README.md
  CIP-0072/version_1_offchain.json
  CIP-0072/version_1_onchain.cddl
  CIP-0072/version_1_onchain.json
Labels: Last Check, Category: Metadata

#497 CPS-0005 | Plutus Script Usability
  CPS-0005/README.md
Labels: Category: Plutus

#505 CIP-0010 | Add label: CIP-0072 (dApp registration & Discovery)
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#380 CIP-1694? | A First Step Towards On-Chain Decentralized Governance
  CIP-1694/README.md
  README.md
Labels: Category: Ledger
