Repository cardano-foundation/CIPs, pull requests merged in 2023-03, with the labels that each got.

#470 CIP-0058 | Put in correctly named directory
  CIP-0058/README.md
  README.md
Labels: Correction

#476 CIP-0058 | Fix metadata in preamble
  CIP-0058/README.md
Labels: Update

#471 CIP-0068 | Clarify label prefixes
  CIP-0068/README.md
Labels: Update

#446 CIP-0030 | Upgrade to latest format & propose version / extension scheme
  CIP-0030/README.md
  README.md
Labels: Update, Last Check, Category: Wallets

#478 Update top-level README with latest statuses.
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#372 CIP-0080? | Transaction Serialization Deprecation Cycle
  CIP-0080/README.md
  README.md
Labels: Last Check, Category: Ledger

#422 CIP-0082? | Improved Rewards Scheme Parameters
  CIP-0082/README.md
  CIP-Improved_Rewards_Scheme_Parameters/ImprovedRewardsSchemeParameters.xlsx
Labels: Last Check

#483 Remove Frederic Johnson from CIP editors
  CIP-0001/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#482 Remove RSS category, use Ledger for CIP-0075 & CIP-0082
  CIP-0001/README.md
  CIP-0075/README.md
  CIP-0082/README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#487 Fix broken links from CIPs to hydra.iohk.io
  CIP-0006/README.md
  CIP-0025/README.md
  CIP-0059/README.md
  CIP-0074/README.md
  CIP-1854/README.md
  CIP-1855/README.md
Labels: Correction
