Repository cardano-foundation/CIPs, pull requests merged in 2024-01, with the labels that each got.

#645 CIP-0006 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0006/README.md
Labels: Remediation

#672 CIP-0026 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0026/README.md
Labels: Remediation

#692 CIP-0035 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0035/README.md
Labels: Remediation

#395 CIP-0045? | Decentralized WebRTC dApp-Wallet Communication
  CIP-0045/README.md
Labels: Category: Wallets

#698 CIP-0042 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0042/README.md
Labels: Remediation

#729 CIP-1855 | Adjust preamble and structure w.r.t CIP-0001
  CIP-1855/README.md
Labels: Remediation

#664 CIP-0019 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0019/README.md
Labels: Remediation

#662 CIP-0017 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0017/README.md
Labels: Remediation

#732 CIP-0036 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0036/README.md
  README.md
Labels: Remediation

#727 CIP-1854 | Adjust preamble and structure w.r.t CIP-0001
  CIP-1854/README.md
Labels: Remediation

#674 CIP-0027 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0027/README.md
Labels: Remediation

#643 CIP-0018 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0018/README.md
Labels: Remediation

#647 CIP-0020 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0020/README.md
Labels: Remediation

#648 CIP-0008 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0008/README.md
Labels: Remediation

#650 CIP-0009 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0009/README.md
Labels: Remediation

#652 CIP-0010 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0010/README.md
Labels: Remediation

#654 CIP-0011 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0011/README.md
Labels: Remediation

#656 CIP-0012 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0012/README.md
Labels: Remediation

#658 CIP-0014 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0014/README.md
Labels: Remediation

#660 CIP-0016 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0016/README.md
Labels: Remediation

#666 CIP-0021 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0021/README.md
Labels: Remediation

#668 CIP-0022 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0022/README.md
Labels: Remediation

#678 CIP-0029 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0029/README.md
Labels: Remediation

#683 CIP-0031 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0031/README.md
Labels: Remediation

#685 CIP-0032 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0032/README.md
Labels: Remediation

#688 CIP-0033 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0033/README.md
Labels: Remediation

#690 CIP-0034 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0034/README.md
Labels: Remediation

#694 CIP-0037 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0037/README.md
Labels: Remediation

#700 CIP-0049 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0049/README.md
Labels: Remediation

#702 CIP-0052 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0052/README.md
Labels: Remediation

#705 CIP-0054 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0054/README.md
Labels: Remediation

#707 CIP-0055 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0055/README.md
Labels: Remediation

#709 CIP-0059 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0059/README.md
Labels: Remediation

#711 CIP-0060 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0060/README.md
Labels: Remediation

#713 CIP-0067 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0067/README.md
Labels: Remediation

#715 CIP-0068 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0068/README.md
Labels: Remediation

#717 CIP-0071 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0071/README.md
Labels: Remediation

#719 CIP-0381 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0381/README.md
Labels: Remediation

#723 CIP-1852 | Adjust preamble and structure w.r.t CIP-0001
  CIP-1852/README.md
Labels: Remediation

#725 CIP-1853 | Adjust preamble and structure w.r.t CIP-0001
  CIP-1853/README.md
Labels: Remediation

#670 CIP-0025 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0025/README.md
Labels: Remediation

#676 CIP-0028 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0028/README.md
Labels: Remediation

#696 CIP-0040 | Adjust preamble and structure w.r.t CIP-0001
  CIP-0040/README.md
Labels: Remediation

#703 CIP-0095 | Promote CIP and update links
  CIP-0095/README.md
  README.md
Labels: Category: Wallets

#740 Update top-level README: post meeting #79
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#737 CIP-0005 | Distinguish between key based and script based conway credentials
  CIP-0005/README.md
  CIP-0105/README.md
Labels: Category: Tools

#745 CIP-1694 | Correctly characterise delegated active stake
  CIP-1694/README.md
Labels: Correction

#746 CIP-1694 | French - Correctly characterise delegated active stake
  CIP-1694/README.fr.md
Labels: Correction

#736 CIP-0100 | Small clean up on example files
  CIP-0100/README.md
  CIP-0100/cip-0100.common.jsonld
  CIP-0100/cip-0100.common.schema.json
  CIP-0100/example.body.canonical
  CIP-0100/example.canonical
  CIP-0100/example.json
Labels: Correction, Category: Metadata

#730 CIP-0001 | Structure and template revisions
  .github/CIP-TEMPLATE.md
  .github/CPS-TEMPLATE.md
  CIP-0001/README.md
Labels: Update

#750 Update top-level README: post meeting #80
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
