Repository cardano-foundation/CIPs, pull requests merged in 2024-05, with the labels that each got.

#795 CIP-0083 | confirm openssl behaviour, fix command line example
  CIP-0083/README.md
Labels: Category: Metadata

#797 Update top-level README: post meeting #86
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#805 Update top-level README: post meeting #87
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#799 CIP-0010 | Add Clarity (DAO creation) metadata label
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#766 CIP-0116? | Universal JSON Encoding for Domain Types
  CIP-0116/README.md
  CIP-0116/cardano-babbage.json
  CIP-0116/changelog.md
Labels: Last Check, Category: Tools

#588 CIP-0104? | Web-Wallet Bridge - Account public key
  CIP-0104/README.md
Labels: Last Check, Category: Wallets

#749 CIP-0112? | Observe script type
  cip-observe-script-type/README.md
Labels: Last Check, Category: Plutus

#800 CIP-1694 | Bootstrap & other fixes
  CIP-1694/README.md
Labels: Last Check

#828 CIP-0010 | Add oracle tx metadata tag to registry
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#820 Update top-level README: post meeting #88
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#788 CIP-0119? | Governance Metadata - DReps
  CIP-0119/README.md
  CIP-0119/cip-0119.common.jsonld
  CIP-0119/cip-0119.common.schema.json
  CIP-0119/examples/drep.jsonld
  CIP-0119/examples/drep.nq
  CIP-0119/test-vector.md
Labels: Category: Metadata

#587 CIP-0103? | Web-Wallet Bridge - Bulk transaction signing
  CIP-0103/README.md
Labels: Last Check, Category: Wallets

#830 CIP-0112 | Fix non-compliant directory name
  CIP-0112/README.md
Labels: Correction

#829 Update top-level README: post meeting #89
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
