Repository cardano-foundation/CIPs, pull requests merged in 2024-02, with the labels that each got.

#756 CIP-9999 | Structure and template revisions
  .github/CPS-TEMPLATE.md
  CIP-9999/README.md
Labels: Category: Meta

#679 CIP-0110? | Plutus v1 compatible script references
  CIP-0110/README.md
Labels: Last Check, Category: Plutus

#622 CIP-1694 | Guard security-relevant protocol parameter changes behind SPO votes
  CIP-1694/README.md
Labels: Category: Ledger

#619 CPS-0010? | Wallet Connectors
  CPS-0010/README.md
  CPS-0010/full-data-wallet.drawio.png
  CPS-0010/no-data-wallet.drawio.png
  CPS-0010/own-data-wallet.drawio.png
Labels: Last Check, Category: Wallets

#641 CIP-0109? | Modular Exponentiation Built-in for Plutus Core
  CIP-0109/README.md
Labels: Last Check, Category: Plutus

#760 Update top-level README: post meeting #81
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#761 CIP-1694 | French - Guard security-relevant protocol parameter change…
  CIP-1694/README.fr.md
Labels: Translation

#762 CIP-9999 | Add mandatory Copyright + related cleanup
  .github/CPS-TEMPLATE.md
  CIP-0001/LICENSE
  CIP-0001/README.md
  CIP-0005/LICENSE
  CIP-0005/README.md
  CIP-0016/LICENSE
  CIP-9999/LICENSE
  CIP-9999/README.md
Labels: Update, Category: Meta

#638 CPS-0013? | Better builtin data structures in Plutus
  CIP-????/README.md
Labels: Last Check, Category: Plutus
