Repository cardano-foundation/CIPs, pull requests merged in 2024-04, with the labels that each got.

#776 CIP-0100 | Move Acknowledgements into optional section
  CIP-0100/README.md
Labels: Update

#764 add License field + Copyright section to all CPSs
  CPS-0005/README.md
  CPS-0007/README.md
  CPS-0010/README.md
  CPS-0011/README.md
  CPS-0013/README.md
Labels: Update

#778 CIP-95, CIP-105, CPS-10 | Update CIPs/CPSs to reflect new optional sections + update email
  CIP-0095/README.md
  CIP-0105/README.md
  CPS-0010/README.md
Labels: Update

#792 Update top-level README: post meeting #85
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#632 CIP-0108? | Governance Metadata - Governance Actions
  CIP-0108/README.md
  CIP-0108/cip-0108.common.jsonld
  CIP-0108/cip-0108.common.schema.json
  CIP-0108/examples/no-confidence.body.canonical
  CIP-0108/examples/no-confidence.body.jsonld
  CIP-0108/examples/no-confidence.canonical
  CIP-0108/examples/no-confidence.jsonld
  CIP-0108/examples/treasury-withdrawal.body.canonical
  CIP-0108/examples/treasury-withdrawal.body.jsonld
  CIP-0108/examples/treasury-withdrawal.canonical
  CIP-0108/examples/treasury-withdrawal.jsonld
  CIP-0108/test-vector.md
Labels: Last Check, Category: Metadata

#687 CIP-0021 | Conway update
  CIP-0021/README.md
Labels: Category: Wallets
