Repository cardano-foundation/CIPs, pull requests merged in 2024-03, with the labels that each got.

#742 CPS-0011? | Universal JSON Encoding for Domain Types
  CPS-0011/README.md
Labels: Last Check, Category: Tools

#771 Update top-level README: post meeting #82
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#773 CIP-0088, CIP-0100 | Fix relative pathnames
  CIP-0088/README.md
  CIP-0100/README.md
Labels: Correction

#770 CIP-0057 | Fix schema validation error (strict mode)
  CIP-0057/schemas/plutus-builtin.json
  CIP-0057/schemas/plutus-data.json
Labels: Correction, Category: Metadata

#768 CIP-0057 | Include Plutus V3
  CIP-0057/schemas/plutus-blueprint.json
Labels: Correction, Category: Plutus

#763 CIP-1694 | Move Acknowledgements into optional section
  CIP-0001/README.md
  CIP-1694/README.md
  CIP-9999/README.md
Labels: Update, Last Check

#751 CPS-0014? | Register of CBOR Tags
  CPS-0014/README.md
Labels: Category: Metadata

#775 Update top-level README: post meeting #83
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#611 CPS-0009? | Coin Selection Including Native Tokens
  CPS-0009/README.md
Labels: Last Check, Category: Wallets

#786 CIP-0010 | Register metadata key number: 620
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#787 CPS-0009 | Add link to Cardano Wallet coin selection library
  CPS-0009/README.md
Labels: Correction, Category: Wallets
