Repository cardano-foundation/CIPs, pull requests merged in 2024-11, with the labels that each got.

#932 CIP-1694 | French - SPO pre-defined voting options
  CIP-1694/README.fr.md
Labels: Translation, State: Triage

#915 CIP-0138? | Plutus Core Builtin Type - Array
  CIP-0138/README.md
Labels: State: Last Check, Category: Plutus

#857 CIP-0129? | Governance Identifiers
  CIP-0005/README.md
  CIP-0105/README.md
  CIP-0105/test-vectors/test-vector-1.md
  CIP-0105/test-vectors/test-vector-2.md
  CIP-0105/test-vectors/test-vector-3.md
  CIP-0105/test-vectors/test-vector-4.md
  CIP-0129/README.md
Labels: State: Last Check, Category: Tools

#941 Update top-level README: post meeting 100
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
