Repository cardano-foundation/CIPs, pull requests merged in 2024-10, with the labels that each got.

#920 CIP-0105 | Change to active state
  CIP-0105/README.md
Labels: Update

#924 CIP-0001 | Annual overhaul and process update
  CIP-0001/README.md
  CIP-9999/README.md
  README.md
Labels: Update, State: Last Check, Bi-Weekly Notes / Editorial Housekeeping

#884 CIP-0133? | Plutus support for Multi-Scalar Multiplication over BLS12-381
  CIP-0133/README.md
Labels: State: Last Check, Category: Plutus

#826 CIP-0127? | Integration of `ripemd_160` into Plutus
  CIP-0127/README.md
Labels: State: Last Check, Category: Plutus

#888 CIP-0134? | Cardano URIs - CIP-0019 Address Representation
  CIP-0134/README.md
  CPS-0016/README.md
Labels: State: Last Check, Category: Wallets

#893 CIP-0135? | Disaster Recovery Plan for Cardano Networks
  CIP-0135/README.md
Labels: State: Last Check, Category: Tools

#930 CIP-0101, CIP-0127 | Remove backticks from literals in titles
  CIP-0101/README.md
  CIP-0127/README.md
Labels: Correction, State: Triage

#876 CIP-0137? | Decentralized Message Queue
  CIP-0137/README.md
  CIP-0137/img/overview.jpg
Labels: State: Last Check, Category: Network

#916 CIP-1694 | SPO pre-defined voting options
  CIP-1694/README.md
Labels: Update, State: Last Check, Category: Ledger

#929 Top README: update modtime from #928
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping, State: Triage

#931 Update top-level README: post meeting 99
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
