Repository cardano-foundation/CIPs, pull requests merged in 2024-09, with the labels that each got.

#896 CIP-0059 | Add Chang HF to Features table
  CIP-0059/feature-table.md
Labels: Update

#894 CIP-0119 | Update drep.jsonld (misspelled `hashAlgorithm`)
  CIP-0119/examples/drep.jsonld
Labels: Correction

#890 CIP-108, CIP-100 | Fix and tweak test vectors/example
  CIP-0100/test-vector.md
  CIP-0108/examples/no-confidence.body.nq
  CIP-0108/examples/treasury-withdrawal.body.nq
  CIP-0108/test-vector.md
Labels: Correction, State: Triage

#488 CIP-0124? | Extend token metadata for translations
  CIP-0124/README.md
  CIP-0124/cddl/version_1.cddl
  CIP-0124/cddl/version_2.cddl
Labels: State: Last Check, Category: Metadata

#891 Add Updates section to top level README
  README.md
Labels: State: Last Check, Bi-Weekly Notes / Editorial Housekeeping

#459 CIP-0091? | Don't force Built-In functions
  CIP-0091/README.md
Labels: State: Last Check, Category: Plutus

#625 CPS-0012? | Query Layer Standardization
  CPS-0012/README.md
Labels: State: Last Check, Category: Tools

#899 Update top-level README: post meeting #96
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#875 CIP-0095 | Misspelling of `DeprecatedCertificate`
  CIP-0095/README.md
Labels: Update, State: Last Check, Category: Wallets

#868 CIP-0060 | v3 metadata restructuring
  CIP-0060/README.md
  CIP-0060/cddl/version-3.cddl
Labels: Update, State: Last Check, Category: Metadata

#854 Preparations for Chang upgrade
  CIP-0069/README.md
  CIP-0110/README.md
  CIP-0117/README.md
  CIP-0381/README.md
  CIP-1694/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#901 Remove inactive editors from CIP editors lists
  CIP-0001/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#904 Top-level README, CIP-0001 | Fix table formatting
  CIP-0001/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#905 Add Thomas Vellekoop as a CIP editor
  CIP-0001/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#911 CIP-1694 | French - Preparations for Chang upgrade
  CIP-1694/README.fr.md
Labels: Translation

#910 CIP-0100 | Add 'Community Tooling' to README.md
  CIP-0100/README.md
Labels: Update, State: Triage

#909 CIP-0108 | Add 'Community Tooling' to README.md
  CIP-0108/README.md
Labels: State: Triage

#906 CIP-0010 | Add 10297 label for fida.finance
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry, State: Confirmed

#895 CIP-0054 | Add reference implementation
  CIP-0054/README.md
Labels: Update, State: Last Check, Category: Tokens

#902 CIP-0019 | add note for pointer address removal in Conway
  CIP-0019/CIP-0019-cardano-addresses.abnf
  CIP-0019/README.md
Labels: Update, State: Triage

#907 CIP-0119 | Add rationale and context for `doNotList`
  CIP-0119/README.md
Labels: Update, State: Triage
