Repository cardano-foundation/CIPs, pull requests merged in 2024-06, with the labels that each got.

#809 CIP-0068 | Allow [* bounded_bytes] for images
  CIP-0068/README.md
Labels: Category: Tokens

#833 CIP-0010 | Misspelled keyword for 1694 label
  CIP-0010/registry.json
Labels: Correction

#784 CIP-0069 | add Datum to ScriptContext
  CIP-0069/README.md
Labels: Update, Last Check, Category: Plutus

#747 CIP-0117? | Explicit script return values
  CIP-0117/README.md
Labels: Last Check, Category: Plutus

#624 CIP-0121? | Integer-ByteString conversions
  CIP-0121/README.md
Labels: Last Check, Category: Plutus

#844 Update top-level README: post meeting #90
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#835 CIP-0100, CIP-0108, CIP-0119 | Hash raw content directly
  CIP-0100/README.md
  CIP-0100/example.nq
  CIP-0100/test-vector.md
  CIP-0108/examples/no-confidence.canonical
  CIP-0108/examples/treasury-withdrawal.canonical
  CIP-0108/test-vector.md
  CIP-0119/examples/drep.nq
  CIP-0119/test-vector.md
Labels: Update, Last Check, Category: Metadata

#617 CIP-0106? | Web-Wallet Bridge - Multisig wallets
  CIP-0106/README.md
Labels: Last Check, Category: Wallets

#825 CIP-0123? | Bitwise operations over BuiltinByteString
  CIP-0123/README.md
Labels: Last Check, Category: Plutus
