Repository cardano-foundation/CIPs, pull requests merged in 2024-07, with the labels that each got.

#849 Update top-level README: post meeting #91
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#840 CIP-0105 | Add missing test vectors
  CIP-0105/README.md
  CIP-0105/test-vectors.md
  CIP-0105/test-vectors/test-vector-1.md
  CIP-0105/test-vectors/test-vector-2.md
  CIP-0105/test-vectors/test-vector-3.md
  CIP-0105/test-vectors/test-vector-4.md
Labels: Category: Wallets

#848 CIP-0102 | Reference Implementation
  CIP-0102/README.md
  CIP-0102/ref_impl/TODO.md
Labels: Last Check, Category: Tokens

#847 CIP-1694 | Updates and semantics
  CIP-1694/README.md
Labels: Last Check

#635 CIP-0107? | URI Scheme - Block and transaction objects
  CIP-0107/README.md
Labels: Last Check, Category: Tools

#859 CIP-0057 | Add 'compiler' field
  CIP-0057/README.md
  CIP-0057/schemas/plutus-blueprint.json
Labels: Update, Last Check

#864 CIP-0122 | Typographical fixes & corrections
  CIP-0122/README.md
Labels: Update

#841 CPS-0016? | Cardano URIs
  CPS-0016/README.md
Labels: Category: Tools

#866 CIP-1694 | French - Updates and semantics
  CIP-1694/README.fr.md
Labels: Translation
