Repository cardano-foundation/CIPs, pull requests merged in 2024-08, with the labels that each got.

#877 Update top-level README: post meeting #94
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#758 CIP-0128? | Preserving Order of Transaction Inputs
  CIP-0128/README.md
Labels: State: Last Check, Category: Plutus

#881 Add top level CONTRIBUTING file
  CONTRIBUTING
Labels: Bi-Weekly Notes / Editorial Housekeeping

#882 CIP-0013 | Acceptance Criteria: add more implementations
  CIP-0013/README.md
Labels: Update, Category: Wallets, State: Confirmed

#886 Update top-level README: post meeting #95
  CPS-0008/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#887 Change top-level README to use dynamically generated lists
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#500 CIP-0010 | Add label: On-chain certification metadata
  CIP-0010/registry.json
Labels: CIP-0010: new registry entry

#892 CIP-0100 | Fix typo in signature method
  CIP-0100/README.md
Labels: Correction
