Repository cardano-foundation/CIPs, pull requests merged in 2025-01, with the labels that each got.

#950 CIP-0119 | Add "@" to the "@type" field of "references"
  CIP-0119/README.md
  CIP-0119/cip-0119.common.schema.json
Labels: Update, State: Last Check, Category: Metadata

#951 CIP-0108 | Ensure "CIP-0008" is in capital letters
  CIP-0108/examples/no-confidence.jsonld
  CIP-0108/test-vector.md
Labels: Update, State: Last Check, Category: Metadata

#796 CIP-0120? | Constitution specification
  CIP-0120/README.md
  CIP-0120/examples/malicious-consitution/cardano-constitution-5.txt
  CIP-0120/examples/malicious-consitution/malicious-rendered.png
  CIP-0120/examples/ryan-consitution/cardano-constitution-0.txt
  CIP-0120/examples/ryan-consitution/ryan-rendered.png
  CIP-0120/test-vector.md
Labels: State: Last Check, Category: Metadata

#878 CIP-0136? | Governance metadata - Constitutional Committee vote rationale
  CIP-0136/README.md
  CIP-0136/cip-136.common.jsonld
  CIP-0136/cip-136.common.schema.json
  CIP-0136/examples/treasury-withdrawal-unconstitutional.body.jsonld
  CIP-0136/examples/treasury-withdrawal-unconstitutional.body.nq
  CIP-0136/examples/treasury-withdrawal-unconstitutional.jsonld
  CIP-0136/test-vector.md
Labels: State: Last Check, Category: Metadata

#912 CIP-0116 | Add Conway JSON schema
  CIP-0116/cardano-babbage.json
  CIP-0116/cardano-conway.json
Labels: Update, State: Last Check, Category: Tools

#922 CPS-0017? | Settlement Speed
  CPS-0017/README.md
Labels: State: Last Check, Category: Consensus

#959 Update top-level README: post meeting 103
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping
