Repository cardano-foundation/CIPs, pull requests merged in 2025-07, with the labels that each got.

#1046 Update top-level README: post meeting 113
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#1047 CIP-0137 | Fix mini-protocols and update implementation plan
  CIP-0137/README.md
Labels: Update, Category: Network

#1044 CIP-0001, CIP-9999, README & templates: periodic update
  .github/CIP-TEMPLATE.md
  .github/CPS-TEMPLATE.md
  CIP-0001/README.md
  CIP-9999/README.md
  README.md
Labels: Update, State: Last Check, Category: Meta

#869 CIP-0139? | Universal Query Layer
  CIP-0139/Query_Layer_API_Comparison.md
  CIP-0139/README.md
  CIP-0139/cip-0144.md
  CIP-0139/endpoints.md
  CIP-0139/json-rpc.json
  CIP-0139/open-api.json
  CIP-0139/query-layer.json
  CIP-0139/ts-api.md
Labels: State: Last Check, Category: Tools

#1011 CIP-0153? | Plutus Core `MaryEraValue` Builtins
  CIP-0153/README.md
Labels: State: Last Check, Category: Plutus

#798 CIP-0141? | Web-Wallet Bridge - Plutus wallets
  CIP-0141/README.md
Labels: State: Last Check, Category: Wallets

#1053 Update top-level README: post meeting 115
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#1051 CIP-0010: Change Reeve metadata label after the official launch
  CIP-0010/registry.json
Labels: State: Last Check, CIP-0010: new registry entry

#1042 CIP-0050 | Modernization & Additional Research
  CIP-0050/README.es.md
  CIP-0050/README.md
  CIP-0050/images/CIP50Formula.png
  CIP-0050/images/RSS1.png
  CIP-0050/images/RSS2.png
  CIP-0050/images/RSS3.png
  CIP-0050/images/RSS4.png
  CIP-0050/images/RewardsFormula.png
  CIP-0050/images/a0 0.0 minfee 0.png
  CIP-0050/images/a0 0.0 minfee 340.png
  CIP-0050/images/a0 0.1 minfee 340.png
  CIP-0050/images/a0 0.2 minfee 340.png
  CIP-0050/images/a0 0.3 minfee 0.png
  CIP-0050/images/a0 0.3 minfee 30.png
  CIP-0050/images/a0 0.3 minfee 340.png
  CIP-0050/images/a0 0.5 minfee 340.png
  CIP-0050/images/a0 1.0 minfee 340.png
  CIP-0050/images/a0 10.0 minfee 340.png
  CIP-0050/images/a0 100 minfee 0.png
  CIP-0050/images/a0 100 minfee 30.png
  CIP-0050/images/chart constant leverage L 100 minfee 0 bias 0.05.png
  CIP-0050/images/chart constant leverage L 100 minfee 0 bias 0.10.png
  CIP-0050/images/chart constant leverage L 100 minfee 0 bias 0.50.png
  CIP-0050/images/chart constant leverage L 100 minfee 0.png
  CIP-0050/images/chart constant leverage L 100 minfee 30 bias 0.05.png
  CIP-0050/images/chart constant leverage L 100 minfee 30 bias 0.10.png
  CIP-0050/images/chart constant leverage L 100 minfee 30.png
  CIP-0050/images/chart current equation a0 0.0 minfee 0.png
  CIP-0050/images/chart current equation a0 0.0 minfee 340.png
  CIP-0050/images/chart current equation a0 0.1 minfee 340.png
  CIP-0050/images/chart current equation a0 0.2 minfee 340.png
  CIP-0050/images/chart current equation a0 0.3 minfee 0.png
  CIP-0050/images/chart current equation a0 0.3 minfee 1000.png
  CIP-0050/images/chart current equation a0 0.3 minfee 2000.png
  CIP-0050/images/chart current equation a0 0.3 minfee 30.png
  CIP-0050/images/chart current equation a0 0.3 minfee 340.png
  CIP-0050/images/chart current equation a0 0.5 minfee 340.png
  CIP-0050/images/chart current equation a0 1.0 minfee 340.png
  CIP-0050/images/chart current equation a0 10.0 minfee 340.png
  CIP-0050/images/equation1.png
  CIP-0050/images/equation2-supporting.png
  CIP-0050/images/equation2.png
  CIP-0050/images/equation3-newRewardEq.png
  CIP-0050/images/equation4-currentEq.png
  CIP-0050/images/equation4-newRewardsEq.png
  CIP-0050/images/equation4-newRewardsEqBiased.png
  CIP-0050/images/equation5-cip7-currentEq.png
  CIP-0050/images/equation8-nimer-adalink.png
  CIP-0050/images/k-effective-table.png
  CIP-0050/images/k-effective.png
  CIP-0050/images/new equation.png
  CIP-0050/images/stake vs leverage current.png
  CIP-0050/images/stake vs leverage proposed.png
  CIP-0050/pool-ranking/pool-ranking-analysis.xlsx
Labels: Update, State: Last Check, Category: Ledger

#1056 CIP-108 CIP-136 | Small schema fixes
  CIP-0108/cip-0108.common.schema.json
  CIP-0136/cip-136.common.schema.json
Labels: Update, State: Last Check, Category: Metadata

#1062 Update top-level README: post meeting 116
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#1067 CIP-0149 | Fix reward order of magnitude
  CIP-0149/README.md
Labels: Correction, State: Last Check, Category: Metadata
