Repository cardano-foundation/CIPs, pull requests merged in 2025-08, with the labels that each got.

#972 CIP-0142? | Web-Wallet Bridge - Network Determination
  CIP-0142/README.md
Labels: State: Last Check, Category: Wallets

#1071 Update top-level README: "ghost" meeting 117
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#946 CIP-0152? | Modules in UPLC
  CIP-0152/README.md
Labels: State: Last Check, Category: Plutus
