Repository cardano-foundation/CIPs, pull requests merged in 2025-05, with the labels that each got.

#991 CIP-0149? | Optional DRep Compensation
  CIP-0149/README.md
Labels: State: Last Check, Category: Metadata

#1032 CIP-100 | update CIP status and add clarification to best practices
  CIP-0100/README.md
Labels: Update, State: Last Check

#1035 CIP-0010 | Add DRep compensation metadatum tag
  CIP-0010/registry.json
Labels: Category: Metadata

#1037 Update top-level README: post meeting 111
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#1038 CIP-0035 | Remove serialization & costing requirements, apply to CIP-0138
  CIP-0035/README.md
  CIP-0138/README.md
Labels: Update, State: Last Check, Category: Plutus

#1036 CIP-0005 | Define bech32 prefixes for extended pool operator keys
  CIP-0005/README.md
Labels: State: Last Check, Category: Tools
