Repository cardano-foundation/CIPs, pull requests merged in 2025-04, with the labels that each got.

#1013 CIP-0137 | Update mini-protocols and implementation plan
  CIP-0137/README.md
Labels: Update, State: Last Check, Category: Network

#466 CIP-0089? | Distributed Dapps & Beacon Tokens
  CIP-0089/README.md
Labels: Category: Tools

#1019 CIP-0052 | Add CertiK to the auditors list
  CIP-0052/README.md
Labels: Update, State: Triage

#1016 CPS-0003 | Withdraw candidate CIP-0125 as solution
  CPS-0003/README.md
Labels: Update, Category: Tokens

#1015 Update top-level README: post meeting 109
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping, State: Triage

#1018 CIP-0060 | Example track_number: change string to integer
  CIP-0060/README.md
Labels: Update, Category: Metadata

#1022 CIP-0008 | fix mesh implementor link and fix one typo
  CIP-0008/README.md
Labels: Correction, State: Triage

#1009 CPS-0021? | Ouroboros Randomness Manipulation
  CPS-0021/CPD/README.md
  CPS-0021/CPD/graph/forking_probabilities.py
  CPS-0021/CPD/graph/mixing_probabilities.py
  CPS-0021/CPD/graph/scenario_cost-graph.py
  CPS-0021/CPD/graph/scenario_cpu_graph.py
  CPS-0021/CPD/graph/window0_graph.py
  CPS-0021/CPD/image/epoch-structure-praos.png
  CPS-0021/CPD/image/grinding-depth-vs-NCPU.png
  CPS-0021/CPD/image/grinding-depth-vs-opportunity-window.png
  CPS-0021/CPD/image/grinding-depth-vs-stake.png
  CPS-0021/CPD/image/grinding-model.png
  CPS-0021/CPD/image/grinding-opportunity-window.png
  CPS-0021/CPD/image/grinding-opportunity.png
  CPS-0021/CPD/image/grinding_depth_comparison.png
  CPS-0021/CPD/image/grinding_depth_scenarios_cost_with_feasibility_layers_gradient.png
  CPS-0021/CPD/image/grinding_depth_scenarios_with_delta.png
  CPS-0021/CPD/image/grinding_forking_attempts_comparison.png
  CPS-0021/CPD/image/grinding_forking_probabilities.png
  CPS-0021/CPD/image/grinding_forking_years.png
  CPS-0021/CPD/image/grinding_mixing_probabilities.png
  CPS-0021/CPD/image/grinding_mixing_years.png
  CPS-0021/CPD/image/grinding_moment.png
  CPS-0021/CPD/image/grinding_power_comparison.png
  CPS-0021/CPD/image/high-level-ledger-structure.png
  CPS-0021/CPD/image/mixing-strategy.png
  CPS-0021/CPD/image/proba_controlling_majority_x_blocks.png
  CPS-0021/CPD/image/slot-leader-distribution-selection.png
  CPS-0021/CPD/image/table-legend.png
  CPS-0021/README.md
Labels: State: Confirmed, Category: Consensus

#1023 CIP-0089 | Fix repo links: options & aftermarket
  CIP-0089/README.md
Labels: Correction, State: Triage

#993 CIP-0150? | Block Data Compression
  CIP-0150/README.md
  CIP-0150/compression-ratio.png
  CIP-0150/decode-speed.png
  CIP-0150/encode-speed.png
  CIP-0150/propagation-3-round.png
  CIP-0150/propagation-4-round.png
  CIP-0150/stats.json
Labels: State: Last Check, Category: Network

#1024 Update top-level README: post meeting 110
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#1025 CPS-0021 | Fix inappropriate status
  CPS-0021/README.md
Labels: Correction, State: Triage

#1029 CIP-0137 | Update local notification N2C mini-protocol
  CIP-0137/README.md
Labels: Update, State: Last Check, Category: Network
