Repository cardano-foundation/CIPs, pull requests merged in 2025-02, with the labels that each got.

#947 CPS-0003? | Smart tokens
  CPS-0003/README.md
Labels: State: Last Check, Category: Tokens

#965 CIP-0005 | Typos and tidy of deprecated governance prefixes
  CIP-0005/README.md
Labels: Correction, State: Last Check

#983 Update top-level README: post meeting 105
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#985 Update CIP Statuses to reflect changes from Plomin hardfork
  CIP-0122/README.md
  CIP-0123/README.md
  CIP-0127/README.md
  CIP-1694/README.md
  README.md
Labels: Bi-Weekly Notes / Editorial Housekeeping

#987 CIP-0129 | Improve gov action id description and examples clarity
  CIP-0129/README.md
Labels: Correction, State: Last Check, Category: Tools

#973 CIP-0010 | Add 21325 label for PRISM
  CIP-0010/registry.json
Labels: State: Last Check, CIP-0010: new registry entry, State: Confirmed

#988 CPS-0003 | Remove deprecated candidate CIP-0143 as solution
  CPS-0003/README.md
Labels: Correction, State: Last Check, Category: Tokens

#925 CPS-0018? | Greater Transaction Throughput
  CPS-0018/README.md
  CPS-0018/images/block-ex-run.svg
  CPS-0018/images/block-mem.svg
  CPS-0018/images/block-memory-epoch.svg
  CPS-0018/images/block-run.svg
  CPS-0018/images/block-size-1blk.svg
  CPS-0018/images/block-size-6hr.svg
  CPS-0018/images/block-size-6min.svg
  CPS-0018/images/block-size.svg
  CPS-0018/images/block-steps-epoch.svg
  CPS-0018/images/block-steps.svg
Labels: State: Last Check, Category: Consensus

#980 CIP-0030 | Add register to track accepted extensions
  CIP-0030/README.md
  CIP-0030/extensions-register.md
Labels: State: Last Check, Category: Wallets

#992 CIP-1694 | French - Update CIP Statuses to reflect changes from Plomin hardfork
  CIP-1694/README.fr.md
Labels: Translation
